https://www.kaggle.com/c/otto-group-product-classification-challenge

Base com 93 parâmetros e o target

O objetivo foi selecionar e reduzir a quantidade desses parâmetros

Para isso foram utilizados:

* Chi Quadrado
* RFE
* Random Forest
* Variance Threshold

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

,id,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_85,feat_86,feat_87,feat_88,feat_89,feat_90,feat_91,feat_92,feat_93,target
0,1,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,Class_1
1,2,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,Class_1
2,3,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,Class_1
3,4,1,0,0,1,6,1,5,0,0,...,0,1,2,0,0,0,0,0,0,Class_1
4,5,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,Class_1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61878 entries, 0 to 61877
Data columns (total 95 columns):
id         61878 non-null int64
feat_1     61878 non-null int64
feat_2     61878 non-null int64
feat_3     61878 non-null int64
feat_4     61878 non-null int64
feat_5     61878 non-null int64
feat_6     61878 non-null int64
feat_7     61878 non-null int64
feat_8     61878 non-null int64
feat_9     61878 non-null int64
feat_10    61878 non-null int64
feat_11    61878 non-null int64
feat_12    61878 non-null int64
feat_13    61878 non-null int64
feat_14    61878 non-null int64
feat_15    61878 non-null int64
feat_16    61878 non-null int64
feat_17    61878 non-null int64
feat_18    61878 non-null int64
feat_19    61878 non-null int64
feat_20    61878 non-null int64
feat_21    61878 non-null int64
feat_22    61878 non-null int64
feat_23    61878 non-null int64
feat_24    61878 non-null int64
feat_25    61878 non-null int64
feat_26    61878 non-null int64
feat_27    61878 non-null int64
feat_28    61878 non-null int64
feat_29    61878 non-null int64
feat_30    61878 non-null int64
feat_31    61878 non-null int64
feat_32    61878 non-null int64
feat_33    61878 non-null int64
feat_34    61878 non-null int64
feat_35    61878 non-null int64
feat_36    61878 non-null int64
feat_37    61878 non-null int64
feat_38    61878 non-null int64
feat_39    61878 non-null int64
feat_40    61878 non-null int64
feat_41    61878 non-null int64
feat_42    61878 non-null int64
feat_43    61878 non-null int64
feat_44    61878 non-null int64
feat_45    61878 non-null int64
feat_46    61878 non-null int64
feat_47    61878 non-null int64
feat_48    61878 non-null int64
feat_49    61878 non-null int64
feat_50    61878 non-null int64
feat_51    61878 non-null int64
feat_52    61878 non-null int64
feat_53    61878 non-null int64
feat_54    61878 non-null int64
feat_55    61878 non-null int64
feat_56    61878 non-null int64
feat_57    61878 non-null int64
feat_58    61878 non-null int64
feat_59    61878 non-null int64
feat_60    61878 non-null int64
feat_61    61878 non-null int64
feat_62    61878 non-null int64
feat_63    61878 non-null int64
feat_64    61878 non-null int64
feat_65    61878 non-null int64
feat_66    61878 non-null int64
feat_67    61878 non-null int64
feat_68    61878 non-null int64
feat_69    61878 non-null int64
feat_70    61878 non-null int64
feat_71    61878 non-null int64
feat_72    61878 non-null int64
feat_73    61878 non-null int64
feat_74    61878 non-null int64
feat_75    61878 non-null int64
feat_76    61878 non-null int64
feat_77    61878 non-null int64
feat_78    61878 non-null int64
feat_79    61878 non-null int64
feat_80    61878 non-null int64
feat_81    61878 non-null int64
feat_82    61878 non-null int64
feat_83    61878 non-null int64
feat_84    61878 non-null int64
feat_85    61878 non-null int64
feat_86    61878 non-null int64
feat_87    61878 non-null int64
feat_88    61878 non-null int64
feat_89    61878 non-null int64
feat_90    61878 non-null int64
feat_91    61878 non-null int64
feat_92    61878 non-null int64
feat_93    61878 non-null int64
target     61878 non-null object
dtypes: int64(94), object(1)
memory usage: 44.8+ MB

In [5]:
df.target.unique()

array(['Class_1', 'Class_2', 'Class_3', 'Class_4', 'Class_5', 'Class_6',
       'Class_7', 'Class_8', 'Class_9'], dtype=object)

In [6]:
df.shape

(61878, 95)

# Seleção de variáveis

In [7]:
X = df.drop(columns=['id', 'target'])

In [8]:
y = df.target

### Chi2

In [9]:
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import MinMaxScaler

In [10]:
x_norm = MinMaxScaler().fit_transform(X)

chi2_selector = SelectKBest(chi2)
chi2_selector.fit(x_norm, y)

chi2_s = chi2_selector.get_support()

chi_feature = X.loc[:,chi2_s].columns.tolist()
print(str(len(chi_feature)), 'variáveis selecionadas:')
print(str(chi_feature))

C:\Users\RobertoMegumi\Anaconda33\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

10 variáveis selecionadas:
['feat_3', 'feat_11', 'feat_14', 'feat_26', 'feat_34', 'feat_39', 'feat_46', 'feat_60', 'feat_69', 'feat_90']

In [11]:
len(chi_feature)

10

### RFE

In [12]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [13]:
rfe_selector = RFE(estimator=LogisticRegression(), step=10)

In [14]:
rfe_selector.fit(X, y)
rfe_support = rfe_selector.get_support()
rfe_feature = X.loc[:,rfe_support].columns.tolist()

print(str(len(rfe_feature)), 'variáveis selecionadas:')
print(str(rfe_feature))

C:\Users\RobertoMegumi\Anaconda33\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\RobertoMegumi\Anaconda33\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\RobertoMegumi\Anaconda33\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\RobertoMegumi\Anaconda33\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\RobertoMegumi\Anaconda33\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\RobertoMegumi\Anaconda33\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\RobertoMegumi\Anaconda33\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\RobertoMegumi\Anaconda33\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\RobertoMegumi\Anaconda33\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\RobertoMegumi\Anaconda33\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\RobertoMegumi\Anaconda33\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\RobertoMegumi\Anaconda33\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

46 variáveis selecionadas:
['feat_6', 'feat_7', 'feat_11', 'feat_14', 'feat_15', 'feat_17', 'feat_21', 'feat_23', 'feat_25', 'feat_26', 'feat_29', 'feat_30', 'feat_34', 'feat_36', 'feat_39', 'feat_40', 'feat_42', 'feat_43', 'feat_45', 'feat_47', 'feat_50', 'feat_51', 'feat_52', 'feat_57', 'feat_58', 'feat_59', 'feat_60', 'feat_61', 'feat_68', 'feat_69', 'feat_72', 'feat_73', 'feat_75', 'feat_76', 'feat_77', 'feat_78', 'feat_81', 'feat_82', 'feat_83', 'feat_84', 'feat_86', 'feat_88', 'feat_90', 'feat_91', 'feat_92', 'feat_93']

### Random Forest

In [15]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier

In [16]:
em_selector = SelectFromModel(RandomForestClassifier(n_estimators=100))
em_selector.fit(X, y)

em_support = em_selector.get_support()
em_feature = X.loc[:, em_support].columns.tolist()

print(str(len(em_feature)), 'variáveis selecionadas:')
print(str(em_feature))

35 variáveis selecionadas:
['feat_3', 'feat_4', 'feat_8', 'feat_9', 'feat_11', 'feat_14', 'feat_15', 'feat_16', 'feat_24', 'feat_25', 'feat_26', 'feat_27', 'feat_32', 'feat_33', 'feat_34', 'feat_36', 'feat_39', 'feat_40', 'feat_42', 'feat_43', 'feat_48', 'feat_53', 'feat_54', 'feat_60', 'feat_62', 'feat_64', 'feat_67', 'feat_68', 'feat_69', 'feat_72', 'feat_75', 'feat_76', 'feat_86', 'feat_88', 'feat_90']

### Variance Threshold

In [17]:
from sklearn.feature_selection import VarianceThreshold

In [18]:
vt_selector = VarianceThreshold(threshold=5)
vt_selector.fit_transform(X)

vt_support = vt_selector.get_support()
vt_feature = X.loc[:, vt_support].columns.tolist()

print(str(len(vt_feature)), 'variáveis selecionadas:')
print(str(vt_feature))

38 variáveis selecionadas:
['feat_3', 'feat_4', 'feat_8', 'feat_9', 'feat_11', 'feat_14', 'feat_15', 'feat_19', 'feat_24', 'feat_25', 'feat_27', 'feat_32', 'feat_34', 'feat_35', 'feat_36', 'feat_39', 'feat_40', 'feat_45', 'feat_46', 'feat_48', 'feat_54', 'feat_58', 'feat_59', 'feat_60', 'feat_62', 'feat_64', 'feat_67', 'feat_69', 'feat_72', 'feat_73', 'feat_74', 'feat_75', 'feat_76', 'feat_78', 'feat_80', 'feat_83', 'feat_86', 'feat_90']

In [19]:
feature_selection_df = pd.DataFrame({'Variáveis': X.columns,
                                 'chi2': chi2_s,
                                 'RFE': rfe_support,
                                 'Random Forest': em_support,
                                 'Variance Threshold': vt_support})

feature_selection_df['Total'] = np.sum(feature_selection_df, axis=1)
feature_selection_df = feature_selection_df.sort_values(['Total', 'Variáveis'], ascending=False)
feature_selection_df

   Variáveis   chi2    RFE  Random Forest  Variance Threshold  Total
89   feat_90   True   True           True                True      4
68   feat_69   True   True           True                True      4
59   feat_60   True   True           True                True      4
38   feat_39   True   True           True                True      4
33   feat_34   True   True           True                True      4
13   feat_14   True   True           True                True      4
10   feat_11   True   True           True                True      4
85   feat_86  False   True           True                True      3
75   feat_76  False   True           True                True      3
74   feat_75  False   True           True                True      3
71   feat_72  False   True           True                True      3
39   feat_40  False   True           True                True      3
35   feat_36  False   True           True                True      3
2     feat_3   True  False           True                True      3
25   feat_26   True   True           True               False      3
24   feat_25  False   True           True                True      3
14   feat_15  False   True           True                True      3
8     feat_9  False  False           True                True      2
87   feat_88  False   True           True               False      2
82   feat_83  False   True          False                True      2
7     feat_8  False  False           True                True      2
77   feat_78  False   True          False                True      2
72   feat_73  False   True          False                True      2
67   feat_68  False   True           True               False      2
66   feat_67  False  False           True                True      2
63   feat_64  False  False           True                True      2
61   feat_62  False  False           True                True      2
58   feat_59  False   True          False                True      2
57   feat_58  False   True          False                True      2
53   feat_54  False  False           True                True      2
..       ...    ...    ...            ...                 ...    ...
18   feat_19  False  False          False                True      1
16   feat_17  False   True          False               False      1
15   feat_16  False  False           True               False      1
88   feat_89  False  False          False               False      0
86   feat_87  False  False          False               False      0
84   feat_85  False  False          False               False      0
78   feat_79  False  False          False               False      0
70   feat_71  False  False          False               False      0
69   feat_70  False  False          False               False      0
65   feat_66  False  False          False               False      0
64   feat_65  False  False          False               False      0
62   feat_63  False  False          False               False      0
55   feat_56  False  False          False               False      0
54   feat_55  False  False          False               False      0
4     feat_5  False  False          False               False      0
48   feat_49  False  False          False               False      0
43   feat_44  False  False          False               False      0
40   feat_41  False  False          False               False      0
37   feat_38  False  False          False               False      0
36   feat_37  False  False          False               False      0
30   feat_31  False  False          False               False      0
27   feat_28  False  False          False               False      0
21   feat_22  False  False          False               False      0
19   feat_20  False  False          False               False      0
1     feat_2  False  False          False               False      0
17   feat_18  False  False          False               False      0
12   feat_13  False  False          False               False      0
11   feat_12  False  False          False               False      0
9    feat_10  False  False          False               False      0
0     feat_1  False  False          False               False      0

[93 rows x 6 columns]

In [20]:
my_features = feature_selection_df[feature_selection_df.Total == 4]['Variáveis'].to_list()
len(my_features)

7

In [21]:
print(my_features)

['feat_90', 'feat_69', 'feat_60', 'feat_39', 'feat_34', 'feat_14', 'feat_11']

In [22]:
expl = df[['feat_90', 'feat_69', 'feat_60', 'feat_39', 'feat_34', 'feat_14', 'feat_11']]

In [23]:
expl.head()

   feat_90  feat_69  feat_60  feat_39  feat_34  feat_14  feat_11
0        0        0       11        0        0        0        1
1        0        0        0        0        0        0        0
2        0        0        0        0        0        0        0
3        0        0        0        0        0        0        1
4        1        0        0        0        0        0        0

# Análise

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(expl, y)

In [26]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((46408, 7), (15470, 7), (46408,), (15470,))

In [27]:
from sklearn.ensemble import GradientBoostingClassifier

In [28]:
model = GradientBoostingClassifier()
model.fit(X_train, y_train)
pred_train = model.predict(X_train)
pred_test = model.predict(X_test)

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
acc_train = round(accuracy_score(pred_train, y_train) * 100, 2)
acc_test = round(accuracy_score(pred_test, y_test) * 100, 2)

print(acc_train)
print(acc_test)

58.86
57.89